name: Push File

on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  copy-file:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Push a file to another repository
      uses: dmnemec/copy_file_to_another_repo_action@v1.1.1
      env:
        API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
      with:
        source_file: 'processed/data_all.csv'
        destination_repo: 'angelicambg/scraping_rselenium'
        destination_folder: 'data'
        user_email: 'angelicambg@gmail.com'
        user_name: 'angelicambg'
        commit_message: 'copy data'

